### ISSUE TITLE
CS50x_2021 pset9 Finance

### ISSUE THREAD

**Issue by arorayash905** [Mayconpm/CS50x_2021#1]
Please update the codes. This one helps to score 55% only.

**Comment by Mayconpm** [comment]
I ask you to check you code, something in your code is wrong. I tested the code and it is 100% correct. 
Remember that the code in here is only as a help on making your code

![me50_Mayconpm - Brave 12_04_2021 16_22_40 (2)](https://user-images.githubusercontent.com/30538403/114449878-af700880-9bab-11eb-80ed-2071d481036d.png)

**Comment by arorayash905** [comment]
I understand, but the exact same code is giving error.
![image](https://user-images.githubusercontent.com/63657713/117540689-f1b32b00-b02d-11eb-8129-04f236597df7.png)
please review, if you can help

**Comment by Mayconpm** [comment]
Once again, I encourage you to make your own code, the codes here are just to guide at times that you have doubts, not to be used in full. This error is raised because of the need for another table, as suggested on the problem page [C$50 Finance](https://cs50.harvard.edu/x/2021/psets/9/finance/)

**Comment by FaizanPasha321** [comment]
This Error is in my code as well, plz explain how to remove it. Thaaanks!

**Comment by arorayash905** [comment]
> This Error is in my code as well, plz explain how to remove it. Thaaanks!

Not yet. Please Let me know if you find the solution to the error.
email - arorayash905@gmail.com
