### ISSUE TITLE
Lab 9 CS50

### ISSUE THREAD

**Issue by andriysvi** [Mayconpm/CS50x_2021#11]
![image](https://github.com/Mayconpm/CS50x_2021/assets/96547612/7c6c0232-9c14-4d19-bd27-5962c9cd6e2c)
Hey, I just copy and pasted your code, because mine didnt worked and i didnt found my fault. But yours also does not seem to work. Do you know the issue with my computer?

**Comment by Mayconpm** [comment]
The errors presented are from some error on your _application.py_, the flask is not recognizing the placeholders on the html file, check your file. My tip is, first try to make the message appear on the screen and then go step by step.
