### ISSUE TITLE
How can I get "helpers.h"? 

### ISSUE THREAD

**Issue by esthicodes** [Mayconpm/CS50x_2021#2]
How do I get this library in my CS50 IDE?

https://github.com/Mayconpm/CS50x_2021/blob/f4f82c5fa44fe9b1963f8310bd2a2b9a06cc0325/pset4/filter/more/helpers.c#L2

**Comment by Mayconpm** [comment]
On the problem page, on the course website, there is all the information you need to get the files you need to solve it.
https://cs50.harvard.edu/x/2021/psets/4/filter/more/
