### ISSUE TITLE
My substitution program is working EXCEPT it prints ! at the end of the ciphertext output - help

### ISSUE THREAD

**Issue by BKRunner** [Mayconpm/CS50x_2021#5]
I've tried everything I can think of - debug, printf, and tinkering endlessly with the code - what's going on?

Here's the "print ciphertext" part of the program:
    {
        printf("ciphertext: ");
        for (int j=0; j<strlen(argv[1]);j++)
        {
        int orig = plain[j];
        int new_char;
        if ((orig > 64)&&(orig < 91))
            {
            int alpha_seq = orig-64;                            //finds alphabetic sequence # for uppercase character
            new_char = toupper(key[(alpha_seq-1)]);             //assigns new letter from key
            }
        else if ((orig > 96)&&(orig<123))
            {
            int alpha_seq = (orig-96);                          //finds alphabetic sequence # for lowercase character
            new_char = tolower(key[(alpha_seq-1)]);             //assigns newe letter from key
            }
        else
            {
            new_char = orig;                                    //leaves non-alpha characters the same
            }
        cipher=(char)new_char;
        printf("%c", cipher);                   //prints cipher character
        }
    }
    printf("\n");

**Comment by Mayconpm** [comment]
Hi! I can only think about the usage of the numbers. I remember  that I had some problem using the number position in the ascii table, so I had to switch to using the functions to check most of the things, maybe some of the operations is breaking something in your code.
