### ISSUE TITLE
Latest solution of Fiftyville (CS50x 2022)

### ISSUE THREAD

**Issue by gauravpdaksh** [Mayconpm/CS50x_2021#8]
Latest solution of Fiftyville (CS50x 2022)-

https://github.com/GauravPDaksh/Harvard_CS50_Programs/tree/main/Problem%20sets/Fiftyville_2022

**Comment by MichalKotus** [comment]
Hi, how do you know, Robin is the accomplice? According to the clue from Raymond, I have got call receivers: 9 people all together. But what are other clues? The accomplice could be anyone among those 9.

Information "The thief then asked the person on the other end of the phone to purchase the flight ticket." does not help me at all. There is no information in DB, who purchased a ticket
